import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import "modern-normalize";

const spartan = League_Spartan({
  variable: "--font-spartan",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Invoice App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={spartan.variable}>{children}</body>
    </html>
  );
}
